
backendURL: $env:backend_url:http://172.17.42.1:5001
precashPaymentInfo: $env:precash_payment_info:Bitte überweise den Betrag von <b>{amount} EUR</b> auf das folgende Konto ...
shippingCosts: $env:shipping_costs:4.90
shippingCostLimit: $env:shipping_cost_limit:80
orderSuccessMailSubject: $env:order_success_mail_subject:Bestätigung der Bestellung
mailCheckFrom: $env:mail_check_from:root@localhost

payPal:
  apiUrl: $env:paypal_api_url:https://api-3t.sandbox.paypal.com/nvp
  redirectUrl: $env:paypal_redirect_url:https://www.sandbox.paypal.com/webscr
  user: $env:paypal_user:info-facilitator_api1.bilderbuch-stoff.de
  pwd: $env:paypal_pwd:FUUPTNBXCF3DQN3R
  signature: $env:paypal_signature:AIzkPgV0CKFumFbqREmlN1svrS-MAtkUOtGFZ6TXz23GBWcUQAI1ylWf
  returnBaseUrl: $env:paypal_return_base_url:http://127.0.0.1:5000/shop/paypalSuccess
  cancelBaseUrl: $env:paypal_cancel_base_url:http://127.0.0.1:5000/shop/orderData

osiamLogin:
  authServerEndpoint: $env:osiam_auth_server_home:http://172.17.42.1:5004/osiam-auth-server/
  resourceServerEndpoint: $env:osiam_resource_server_home:http://172.17.42.1:5004/osiam-resource-server/
  clientId: $env:osiam_client_id:bsweb
  clientSecret: $env:osiam_client_secret:trdjnlkmzt23d21
  sessionCookieSecret: $env:session_secret:secretsecretsecretsecretsecretse
  sessionLifetimeMinutes: $env:session_lifetime_minutes:180

server:
  applicationConnectors:
    - type: http
      port: 5003
  adminConnectors:
    - type: http
      port: 5103

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO,
  # DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    net.mancke: TRACE
