
backendURL: $env:BACKEND_URL:http://172.17.42.1:5001

osiamLogin:
  authServerEndpoint: $env:OSIAM_AUTH_SERVER_HOME:http://127.0.0.1:5101/osiam-auth-server/
  resourceServerEndpoint: $env:OSIAM_RESOURCE_SERVER_HOME:http://127.0.0.1:5102/osiam-resource-server/
  clientId: $env:OSIAM_CLIENT_ID:bsweb
  clientSecret: $env:OSIAM_CLIENT_SECRET:super-secret
  sessionCookieSecret: $env:SESSION_SECRET:e2l21$%678bdwkml
  sessionLifetimeMinutes: $env:SESSION_LIFETIME:180

server:
  applicationConnectors:
    - type: http
      port: 5003
  adminConnectors:
    - type: http
      port: 5004

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO,
  # DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    net.mancke: TRACE
